Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"


	config.vm.network :forwarded_port, guest: 8001, host:8881
	config.vm.network :private_network, ip: "192.168.1.111"

	config.vm.synced_folder "/home/john/Learning/Erlang/VagrantCB", "/home/vagrant/chicagoboss"

	config.vm.provision :shell, path: "bootstrap.sh"

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.name = "chicagoboss"
	end
end
